# This conf is read by lightwalletd to find the zcashd RPC endpoint.
# rpcbind here tells lightwalletd WHERE TO CONNECT (the zcashd container).
regtest=1
rpcuser=zcashrpc
rpcpassword=notsecure
rpcbind=zcashd
rpcport=18232
